### PR TITLE
Optimize anchor plane

### PR DESCRIPTION
**Pull request by ibarbech**
Optimize anchor plane

### CODE REVIEW

**Comment by serengil** [comment]
thank you for your contribution

I can't understand about the change. It does the same with the removed code?

**Comment by ibarbech** [comment]
Yes
This new code replaces the 3 for loops and reduces the time

**Comment by serengil** [comment]
I tested it and see it works but I don't understand how it works :)

Appreciate for your effort.

**Comment by ibarbech** [comment]
I tested it 
and the new code reduce the time from 80 ms to 1.05 ms in my case.

**Comment by serengil** [comment]
Wonderful!

**Pull request merged**
